show databases;

use training_center;
show tables;
create table employee(emp_id int,emp_name varchar(30),department varchar(30),city varchar(30),salary int, experience int);
insert into employee(emp_id,emp_name,department,salary,experience) values(125,'teja','IT',250000,2);
select * from employee;
update employee set city = 'benguluru' where department = 'IT';
select * from employee where salary between 30000 and 60000 and salary != 45000;
select * from employee where department in ('analyst','testing') and city != 'chundi';
select * from employee where emp_name like 'v%y';
select * from employee where emp_name like '_h%u';
select * from employee where salary not between 25000 and 50000 and city != 'hyderabad';
select * from employee where emp_name like '%a%a%';
select * from employee where experience in (2,4,6,8) and department != 'accounts';
select * from employee where city is null or salary > 40000;
select * from employee where emp_name like '%ar%' and emp_name not like 'a%';
select * from employee where salary % 1000 = 0;
select * from employee order by department asc,salary desc;
select * from employee order by city asc,experience desc, salary asc;
select * from employee order by salary desc,emp_name asc;
select * from employee order by salary desc limit 5;
select * from employee order by experience asc,salary desc;
select * from employee where emp_name like 'v%' order by city,salary;
select * from employee order by department,city,emp_name;
select department,count(*) from employee group by department;
select city,avg(salary) from employee group by city;
select department,max(salary),min(salary) from employee group by department;
select city,sum(salary),count(*) from employee group by city;
select department,city,count(*) from employee group by department,city;
select city,max(experience) from employee group by city;
select city,count(*) from employee where salary > 50000 group by city ;
select department,sum(salary) from employee where experience > 3 group by department;
select city,count(*) from employee where department != 'HR' group by city;
select department,count(*) from employee group by department having count(*) > 5;
select city,avg(salary) from employee group by city having avg(salary) > 50000;
select department,max(salary) from employee group by department having max(salary) > 90000;
select city,count(*),avg(experience) from employee group by city having count(*) >= 3 and avg(experience) > 4;
select department,sum(salary) from employee group by department having sum(salary) > 300000;
select city,min(salary) from employee group by city having sum(salary) > 300000;
